// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnR0GQgdN0tAlNdxhMVmZcIo1Rope8qNQ',
    appId: '1:766773810207:web:13906092f8aef11dbaf12a',
    messagingSenderId: '766773810207',
    projectId: 'doce-control',
    authDomain: 'doce-control.firebaseapp.com',
    storageBucket: 'doce-control.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JAUWTbFK-Q0em2uSiQ7GHT8DxeOpXLg',
    appId: '1:766773810207:android:68e835f96ebe755cbaf12a',
    messagingSenderId: '766773810207',
    projectId: 'doce-control',
    storageBucket: 'doce-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXcRi7Q14dFI-2Z2iy-PuymZNPM5bHV8',
    appId: '1:766773810207:ios:a361dff7aea2a510baf12a',
    messagingSenderId: '766773810207',
    projectId: 'doce-control',
    storageBucket: 'doce-control.firebasestorage.app',
    iosBundleId: 'com.example.docecontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXcRi7Q14dFI-2Z2iy-PuymZNPM5bHV8',
    appId: '1:766773810207:ios:a361dff7aea2a510baf12a',
    messagingSenderId: '766773810207',
    projectId: 'doce-control',
    storageBucket: 'doce-control.firebasestorage.app',
    iosBundleId: 'com.example.docecontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnR0GQgdN0tAlNdxhMVmZcIo1Rope8qNQ',
    appId: '1:766773810207:web:d7449641c7ea2f09baf12a',
    messagingSenderId: '766773810207',
    projectId: 'doce-control',
    authDomain: 'doce-control.firebaseapp.com',
    storageBucket: 'doce-control.firebasestorage.app',
  );
}
